version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: fitgenie_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fitgenieai
    networks:
      - fitgenie_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fitgenie_backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/fitgenieai
    depends_on:
      - mongodb
    networks:
      - fitgenie_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fitgenie_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000/api
    depends_on:
      - backend
    networks:
      - fitgenie_network

networks:
  fitgenie_network:
    driver: bridge

volumes:
  mongodb_data: